import { Footer } from "./Footer/Footer";
import { Loader } from "./Loader/Loader";
import { MovieContainer } from "./MovieContainer/MovieContainer";
import { MovieCard } from "./MovieCard/MovieCard";
import { SingleMovie } from "./SingleMovie/SingleMovie";
export * from "./SingleMovie/DownloadPop";
export * from "./SingleMovie/DownloadButton";
export * from "./SingleMovie/SingleMovieTrailer";
export * from "./SingleMovie/TrailerPopup";
export * from "./SingleMovie/TrailerImg";
export * from "./SingleMovie/SummeryCast";
export * from "./SearchContainer/SearchContainer";
export * from "./SearchContainer/SearchSideBar";
export * from "./SearchContainer/SearchViewBar";
export * from "./SearchContainer/ViewGrid";
export * from "./SearchContainer/ViewFlex";
export * from "./SearchContainer/SearchCard";
export * from "./Header/Header2";

export { Footer, MovieContainer, Loader, MovieCard, SingleMovie };
